x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}

services:
    web:
        <<: *base-service
        restart: on-failure
        env_file:
            - .env
            - .env.production
            - .env.production.local
        volumes:
            - ./deploy/envs/.env:/app/.env
            - ./deploy/envs/.env.production:/app/.env.production
            - ./deploy/envs/.env.production.local:/app/.env.production.local
        environment:
            NODE_ENV: production
        profiles:
            - default
            - web

    proxy:
        <<: *base-service
        restart: on-failure
        image: ${NGINX_IMG}
        volumes:
            - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./deploy/nginx/templates:/etc/nginx/templates:ro
            - ./certbot/www/:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        env_file:
            - .env.production
        ports:
            - 80:80
            - 443:443
        depends_on:
            web:
                condition: service_started
        profiles:
            - default

    certbot:
        <<: *base-service
        image: certbot/certbot:v2.7.4
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        profiles:
            - default

