x-base-dev-service: &base-dev-service
    restart: "no"
    networks:
        - default

services:
    web:
        <<: *base-dev-service
        build:
            context: .
            dockerfile: deploy/web/Dockerfile
            args:
                img: ${NODE_IMG}
        ports:
            - ${PORT}:3000
        networks:
            - default
            - gabgabgurus_external

    proxy:
        <<: *base-dev-service
        volumes:
            - ./deploy/nginx/templates_dev:/etc/nginx/templates:ro

networks:
    gabgabgurus_external:
        external: true
        name: gabgabgurus_external
