services:
    proxy:
        image: nginx:1.25-alpine-slim
        volumes:
            - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./index.html:/var/www/data/index.html
            #- ./deploy/nginx/templates/ssl/config-step1:/etc/nginx/templates/site.conf.template:ro
            - ./deploy/nginx/templates/ssl/config-redirect:/etc/nginx/templates/site.conf.template:ro
            - /home/denis/gabgabgurus/certbot/www/:/var/www/certbot/:ro
            - /home/denis/gabgabgurus/certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - 80:80
            - 443:443

    certbot:
        image: certbot/certbot:latest
        volumes:
            - /home/denis/gabgabgurus/certbot/www/:/var/www/certbot/:rw
            - /home/denis/gabgabgurus/certbot/conf/:/etc/letsencrypt/:rw
