x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
    restart: on-failure

services:
    web:
        <<: *base-service
        env_file:
            - .env
            - .env.production
            - .env.production.local
        environment:
            NODE_ENV: production
        profiles:
            - default
            - web

    proxy:
        <<: *base-service
        image: ${NGINX_IMG}
        volumes:
            - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./deploy/nginx/templates:/etc/nginx/templates:ro
            - /home/denis/gabgabgurus/certbot/www/:/var/www/certbot/:ro
            - /home/denis/gabgabgurus/certbot/conf/:/etc/nginx/ssl/:ro
        env_file:
            - .env.production
        ports:
            - 80:80
            - 443:443
        depends_on:
            web:
                condition: service_started
        profiles:
            - default

    certbot:
        <<: *base-service
        image: certbot/certbot:v2.7.4
        volumes:
            - /home/denis/gabgabgurus/certbot/www/:/var/www/certbot/:rw
            - /home/denis/gabgabgurus/certbot/conf/:/etc/letsencrypt/:rw
        profiles:
            - default
