x-base-dev-service: &base-dev-service
    restart: "no"
    networks:
        - default

services:
    web:
        <<: *base-dev-service
        build:
            context: .
            dockerfile: deploy/web/Dockerfile
            args:
                IMG: ${NODE_IMG}
                BASE_API_URL: ${NEXT_PUBLIC_BASE_API_URL?Variable not set}
                BASE_WS_URL: ${NEXT_PUBLIC_BASE_WS_URL?Variable not set}
        environment:
            NODE_ENV: production
#            NODE_ENV: development
#        command: ["npm", "run", "dev"]
        volumes:
            - ./.env.development.local:/${WEB_APP_WORK_DIR?Variable not set}/.env.development.local
            - ./.env.production.local:/${WEB_APP_WORK_DIR?Variable not set}/.env.production.local
        ports:
            - ${PORT}:${PORT}

    proxy:
        <<: *base-dev-service
        env_file:
            - .env.development.local
        ports:
            - ${PROXY_LISTEN_PORT}:${PROXY_LISTEN_PORT}
        volumes:
            - ./deploy/nginx/templates_dev:/etc/nginx/templates:ro
