services:
    web:
        image: ${WEB_APP_IMG}
        volumes:
            - ./.env.production.local:/${WEB_APP_WORK_DIR?Variable not set}/.env.production.local

    proxy:
        env_file:
            - .env.production.local
        ports:
            - 80:80
            - 443:443
