x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
    restart: on-failure

services:
    proxy:
        <<: *base-service
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                - img=nginx:1.25-alpine-slim
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/templates:/etc/nginx/templates:ro
            - ./certbot/www/:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - 80:80
            - 443:443

    certbot:
        <<: *base-service
        image: certbot/certbot:v2.7.4
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
