services:
    web:
        image: ${WEB_APP_IMG}
        volumes:
            - ./.env.production.local:/app/.env.production.local

    proxy:
        env_file:
            - .env.production.local
        ports:
            - 80:80
            - 443:443
