x-base-dev-service: &base-dev-service
    restart: "no"
    networks:
        - default

services:
    web:
        <<: *base-dev-service
        build:
            context: .
            dockerfile: deploy/web/Dockerfile
            args:
                img: ${NODE_IMG}
        environment:
            NODE_ENV: development
        command: ["npm", "run", "dev"]
        volumes:
            - ./.env:/app/.env
            - ./.env.development.local:/app/.env.development.local
        ports:
            - ${PORT}:${PORT}

    proxy:
        <<: *base-dev-service
        env_file:
            - .env.development.local
        ports:
            - ${PROXY_LISTEN_PORT}:${PROXY_LISTEN_PORT}
        volumes:
            - ./deploy/nginx/templates_dev:/etc/nginx/templates:ro
