ARG img=node:20.10.0-slim
ARG work_dir=app

FROM ${img} AS deps

#RUN apk add --no-cache libc6-compat
WORKDIR /${work_dir}

COPY package.json package-lock.json ./
RUN  npm install --production

FROM ${img} AS builder
WORKDIR /${work_dir}

COPY --from=deps /${work_dir}/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build


FROM ${img} AS runner
WORKDIR /${work_dir}

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /${work_dir}/.next ./.next
COPY --from=builder /${work_dir}/node_modules ./node_modules
COPY --from=builder /${work_dir}/package.json ./package.json

COPY ./scripts ./scripts
COPY ./docker/web/scripts ./scripts
RUN chmod -R 777 ./scripts

USER nextjs

EXPOSE 3000

ENV PORT 3000


ENTRYPOINT ["./scripts/entrypoint.sh"]

CMD ["npm", "start"]
