name: Deploy-only workflow

env:
    ENVIRONMENT: production
    PYTHON_IMG: python:3.11-slim
    APP_IMG_NAME: ggg-b:latest
    SERVER_PROJECT_ROOT_DIR: /home/denis/gabgabgurus/gabgabgurus-backend

on:
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: 📥 Check out the repo
                uses: actions/checkout@v4

            -   name: 🚀 Deploy to Remote Server
                uses: appleboy/ssh-action@v1.0.0
                env:
                    SERVER_PROJECT_ROOT_DIR: ${{ env.SERVER_PROJECT_ROOT_DIR }}
                    APP_IMG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_IMG_NAME }}
                    COMPOSE_PROJECT_NAME: ${{ secrets.COMPOSE_PROJECT_NAME }}
                with:
                    host: ${{ secrets.PETS_HOST }}
                    username: ${{ secrets.PETS_USERNAME }}
                    key: ${{ secrets.PETS_GHA_KEY }}
                    port: ${{ secrets.PETS_SSH_PORT }}
                    envs: SERVER_PROJECT_ROOT_DIR, APP_IMG, COMPOSE_PROJECT_NAME
                    script_stop: true
                    script: |
                        cd $SERVER_PROJECT_ROOT_DIR
                        git pull
                        docker pull $APP_IMG
                        COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile default down
                        COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile default up -d --build
                        docker system prune -f
