name: Deploy-only workflow

env:
    ENVIRONMENT: production
    APP_IMG_NAME: ggg-w:latest

on:
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: 📥 Check out the repo
                uses: actions/checkout@v4

            -   name: 🚀 Deploy to Remote Server
                uses: appleboy/ssh-action@v1.0.0
                env:
                    SERVER_PROJECT_ROOT_DIR: ${{ secrets.SERVER_PROJECT_ROOT_DIR }}
                    APP_IMG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_IMG_NAME }}
                    COMPOSE_PROJECT_NAME: ${{ secrets.COMPOSE_PROJECT_NAME }}
                    GGG_EXTERNAL_NETWORK: ${{ secrets.GGG_EXTERNAL_NETWORK }}
                with:
                    host: ${{ secrets.PETS_HOST }}
                    username: ${{ secrets.PETS_USERNAME }}
                    key: ${{ secrets.PETS_GHA_KEY }}
                    port: ${{ secrets.PETS_SSH_PORT }}
                    envs: SERVER_PROJECT_ROOT_DIR, APP_IMG, COMPOSE_PROJECT_NAME, GGG_EXTERNAL_NETWORK
                    script_stop: true
                    script: |
                        cd $SERVER_PROJECT_ROOT_DIR
                        git pull
                        . ./deploy/scripts/deploy.sh
#                        docker pull $APP_IMG
#                        docker network create $GGG_EXTERNAL_NETWORK
#                        COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile default down
#                        COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile default up -d --build
#                        docker system prune -f
